[package]
name = "web_stream_engine_rust_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.0"
futures = "0.3.27"
json = "0.12.4"
lazy_static = "1.4.0"
reqwest = "0.11.14"
tokio = { version = "1.26.0", features = ["full"] }
uuid = "1.3.0"
